name: Release

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: 
  push:
    branches:
      - "main"

jobs:
  publish-github-release:
    name: "🔄 Publish Github Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish` Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DIR_ROOT="$(pwd)"
          TAG="$(date -u +"v%Y.%m.%d.%H%M").${GITHUB_SHA::4}"
          echo "Tag: ${TAG}"

          gh release create $TAG  --draft --notes "Automatically built binaries"
          gh release edit $TAG --title "🚀 Latest"

          cd $DIR_ROOT/shells/bash
          tar -czvf * xenv-bash.tar.gz
          gh release upload $TAG xenv-bash.tar.gz

          cd $DIR_ROOT/shells/fish
          tar -czvf * xenv-fish.tar.gz
          gh release upload $TAG xenv-fish.tar.gz

          cd $DIR_ROOT/shells/powershell
          tar -czvf * xenv-powershell.tar.gz
          gh release upload $TAG xenv-powershell.tar.gz
          
          gh release edit $TAG --draft=false
