#!/bin/env bash

if [ -f "$ENV_PATH" ]; then
  echo "Reading $ENV_PATH"
  while read -r LINE; do
    # Remove leading and trailing whitespaces, and carriage return
    CLEANED_LINE=$(echo "$LINE" | awk '{$1=$1};1' | tr -d '\r')

    if [[ $CLEANED_LINE != '#'* ]] && [[ $CLEANED_LINE == *'='* ]]; then
      echo "Setting: $CLEANED_LINE"
      export "$CLEANED_LINE"
    fi
  done < "$ENV_PATH"
fi

